### ISSUE TITLE
Stdlib cannot contain directories

### ISSUE THREAD

**Issue by villesundell** [dfinance/move-tools#166]
Hello!
It seems that if standard library contains directories (like current Diem library does: doc/), the language server bails out with EISDIR, since it tries to read that directory as a regular file.

**Comment by borispovod** [comment]
Hello @villesundell 

Thank you for bug report.

We are looking into issue, and we would try to fix it asap.

**Comment by borispovod** [comment]
Hello @villesundell 

We found issue, it's not in language-server unfortunately, bug happens in [Move IDE](https://github.com/dfinance/vscode-move-ide).

We need little more time to fix, but we will do it asap.

**Comment by borispovod** [comment]
Hey @villesundell 

We published new VSCode extension, there is fixed issue.
You can download by link - https://marketplace.visualstudio.com/items?itemName=PontemNetwork.move-language

We will support Move language extension in the future, active development starting since next week.

**Comment by villesundell** [comment]
Hello @borispovod !
Thank you very much for the fix, and also thank you supporting it in the future :)
